import pytest
import random
from utilities.Custom_logger import LogGen

class TestCategoryModule:
    logger = LogGen.loggen()
    category_id = None
    category_slug = None

    category_name = f"Gadgets {random.randint(100, 200)}"

    def test_create_category(self, categories_client):
        obj = categories_client
        payload = {
            "name": TestCategoryModule.category_name,
            "image": "https://picsum.photos/640/480"
        }
        res = obj.create_category(payload)
        assert res.status ==201
        res_data = res.json()
        assert res_data["name"] == TestCategoryModule.category_name
        TestCategoryModule.category_id = res_data["id"]
        TestCategoryModule.category_slug = res_data.get("slug", "")
        self.logger.info("Category  created and store id ")


    def test_get_category_details(self, categories_client):
        obj = categories_client
        cart_id = TestCategoryModule.category_id
        res = obj.get_category(cart_id)
        assert res.status == 200
        assert res.json()["name"] == TestCategoryModule.category_name
        self.logger.info(" Get Category method verified sucessfully")

    def test_get_category_by_slug(self, categories_client):
            obj  = categories_client
            slug = TestCategoryModule.category_slug
    
            if slug:
                res = obj.get_category_by_slug(slug)
                assert res.status ==200
                assert res.json()["id"] == TestCategoryModule.category_id
                self.logger.info("Get category by slug verified successfully ")
    
            else:
                pytest.skip("Slug not generated by API, skip slug test case")


    def test_get_products_belonging_to_category(self, categories_client):
        obj = categories_client
        cat_id = TestCategoryModule.category_id
        res = obj.get_products_by_category(cat_id)
        assert res.status == 200
        assert isinstance(res.json(), list)
        self.logger.info(f"GET Products by Category verified. Found {len(res.json())} products.")
         

    def test_update_and_delete_category(self, categories_client):
        obj =categories_client
        cart_id = TestCategoryModule.category_id
        upadate_name = f"Updated {TestCategoryModule.category_name}"
        udate_paylod = {"name":  upadate_name}
        res_update =  obj.update_category(cart_id, udate_paylod)

        assert res_update.status ==200
        assert res_update.json()["name"] == upadate_name
        self.logger.info("Put category verified sucessfully")

        # cleanup
        res_delete = obj.delete_category(cart_id)
        assert res_delete.status ==200
        self.logger.info("Delete Category verified successfully")

    

  


